[tool.black]
line-length = 100
skip_string_normalization = true
target_version = ['py27', 'py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | virtualenv
  | virtualenv-py3
  | virtualenv-st2client
  | test_content_version
)/

